# .github/workflows/ai-code-review.yml
name: AI Code Review

on:
  issue_comment:
    types: [created]

jobs:
  review:
    # Run only if comment is on a PR and starts with the trigger command
    if: startsWith(github.event.comment.body, '/ai-review') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    # Permissions needed by the action to read code and write comments
    permissions:
      contents: read
      pull-requests: write
      issues: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Add this Debug Step ---
      - name: List workspace .github directory
        run: |
          echo "Workspace: ${{ github.workspace }}"
          echo "Listing contents of ${{ github.workspace }}/.github:"
          ls -la ${{ github.workspace }}/.github
      # --------------------------

      - name: Run AI Review Bot Action
        id: run_ai_review # Give the step an ID for checking outcome
        uses: abhithind31/ai-review-bot@v5
        with:
          # Pass AWS secrets to the action
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Required if using temporary credentials
          aws-region: ${{ secrets.AWS_REGION }} # e.g., 'us-east-1' or set as secret
          # --- JIRA Integration (Enabled by Default) ---
          # Provide these secrets unless Jira is disabled in the config file.
          jira-url: ${{ secrets.JIRA_URL }}
          jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          # ... other optional inputs ...

      # ... rest of your workflow (e.g., reaction step)
